// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnjncjrlnnmiqhimywcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuam5janJsbm5taXFoaW15d2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTczMTMsImV4cCI6MjA2NTUzMzMxM30.KKr5PDFqrSX5h3R_OwnmpTyc5xScNMQ8_bdB--ABnpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);